## Name: Paras Shah
## Roll number: 25/AFI/08

In [ ]:
import numpy as np
import torch

In [ ]:
# Creating Tensors
## Numpy
a = np.array([1, 2, 3])
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

## Pytorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
z = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(f"1D tensors: \n{a}\n{x}")
print(f"2D tensors: \n{b}\n{y}")
print(f"3D tensors: \n{c}\n{z}")

1D tensors: 
[1 2 3]
tensor([1, 2, 3])
2D tensors: 
[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
3D tensors: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [ ]:
# Element-wise operations
## Numpy
a1 = np.array([4, 5, 6])
print("Numpy operations:")
print(f"Addition: {a + a1}")
print(f"Subtraction: {a - a1}")
print(f"Multiplication: {a * a1}")
print(f"Division: {a / a1}")

## Pytorch
x1 = torch.tensor([4, 5, 6])
print("\nPytorch operations:")
print(f"Addition: {x + x1}")
print(f"Subtraction: {x - x1}")
print(f"Multiplication: {x * x1}")
print(f"Division: {x / x1}")

Numpy operations:
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]

Pytorch operations:
Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


In [ ]:
# Matrix operations
## Numpy
b1 = np.array([
    [1, 2],
    [3, 4]
])
b2 = np.array([
    [5, 6],
    [7, 8]
])
print("Numpy operations:")
print(f"Dot product: {np.dot(a, a1)}")
print(f"Matrix multiplication: \n{b1 @ b2}")

## Pytorch
y1 = torch.tensor([
    [1, 2],
    [3, 4]
])
y2 = torch.tensor([
    [5, 6],
    [7, 8]
])
print("\nPytorch operations:")
print(f"Dot product: {torch.dot(x, x1)}")
print(f"Matrix multiplication: \n{y1 @ y2}")

Numpy operations:
Dot product: 32
Matrix multiplication: 
[[19 22]
 [43 50]]

Pytorch operations:
Dot product: 32
Matrix multiplication: 
tensor([[19, 22],
        [43, 50]])


In [ ]:
# Indexing and slicing
## Numpy
print("Numpy operations:")
print(f"Index 0, 1 of b: {b[0][1]}")
print(f"Slice from -1 to end of c[1]: \n{c[1][-1:]}")
print(f"Boolean masking for value more than 5: \n{b2 > 5}")
print(f"Extract sub-tensor from c: \n{c[0:1][0:1]}")

## Pytorch
print("\nPytorch operations:")
print(f"Index 1 of x: {x[1]}")
print(f"Slice from -1 to end of z: \n{z[-1:]}")
print(f"Boolean masking for value more than 6: \n{y2 > 6}")
print(f"Extract sub-tensor from z: \n{z[0:1][0:1]}")

Numpy operations:
Index 0, 1 of b: 2
Slice from -1 to end of c[1]: 
[[7 8]]
Boolean masking for value more than 5: 
[[False  True]
 [ True  True]]
Extract sub-tensor from c: 
[[[1 2]
  [3 4]]]

Pytorch operations:
Index 1 of x: 2
Slice from -1 to end of z: 
tensor([[[5, 6],
         [7, 8]]])
Boolean masking for value more than 6: 
tensor([[False, False],
        [ True,  True]])
Extract sub-tensor from z: 
tensor([[[1, 2],
         [3, 4]]])


In [ ]:
# Reshaping
## Numpy
print(f"Numpy .reshape(): \n{b.reshape(3, 2)}")

## Pytorch
print(f"\nTorch .view(): \n{y1.view(4, -1)}") # Requires contiguous tensor
print(f"Torch .reshape(): {y2.t().reshape(1, -1)}") # Internally handles non-contiguous tensor
print(f"Torch .squeeze(): {torch.squeeze(torch.randn(3, 1, 2, 4)).size()}") # Remove dimensions of size 1
print(f"Torch .unsqueeze(): {torch.unsqueeze(torch.randn(3, 2, 4), dim=1).size()}") # Add single size dimension at given index

Numpy .reshape(): 
[[1 2]
 [3 4]
 [5 6]]

Torch .view(): 
tensor([[1],
        [2],
        [3],
        [4]])
Torch .reshape(): tensor([[5, 7, 6, 8]])
Torch .squeeze(): torch.Size([3, 2, 4])
Torch .unsqueeze(): torch.Size([3, 1, 2, 4])


In [ ]:
# Broadcasting
## Numpy
print("Numpy operations:")
print(f"Multiplication by 2: {a * 2}")
print(f"Adding a and b: \n{a + b}")

# Pytorch
print("\nPytorch operations:")
print(f"Muliplication by 10: {x * 10}")
print(f"Adding x and 2y: \n{x + 2 * y}")

Numpy operations:
Multiplication by 2: [2 4 6]
Adding a and b: 
[[2 4 6]
 [5 7 9]]

Pytorch operations:
Muliplication by 10: tensor([10, 20, 30])
Adding x and 2y: 
tensor([[ 3,  6,  9],
        [ 9, 12, 15]])


In [ ]:
# In-place and out-of-place operations
## Numpy
print("Numpy operations:")
a2 = a1 + 1
print(f"Out-of-place addition: {a2}")
a1 += 2
print(f"In-place additions: {a1}")

## Pytorch
print("\nPytorch operations:")
x2 = x1 + 1
print(f"Out-of-place addition: {x2}")
x1.add_(2)
print(f"In-place addition: {x1}")

Numpy operations:
Out-of-place addition: [6 7 8]
In-place additions: [7 8 9]

Pytorch operations:
Out-of-place addition: tensor([ 9, 10, 11])
In-place addition: tensor([10, 11, 12])
